apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service-labelname
    app: demo-volting-app
spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: demo-volting-app
  ports:
    - port: 5432
      targetPort: 5432
