apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service-lname
    app: demo-volting-app
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: demo-volting-app
  ports:
    - port: 6379
      targetPort: 6379
