apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-volting-app
spec:
  type: LoadBalancer
  selector:
    name: result-app-pod
    app: demo-volting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005