apiVersion: v1
kind: Pod
metatdata:
  name: myapp-pod
  labels:
    app: myapp-pod
    type: front-end
    env: dev

spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
