apiVersion: v1
kind: Pod
metatdata:
  name: myapp-pod
  labels:
    app: myapp-pod
    type: front-end
    env: dev

spec:
  containers:
    - name: nginx-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In # NotIn OR Exists
                value:
                  - Large
                  - Medium
